import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#8e004c",
        "secondary-fixed": "#ffd9e3",
        "primary-fixed-dim": "#00dce6",
        "secondary-container": "#e1037d",
        "on-tertiary-container": "#004df0",
        "tertiary-fixed-dim": "#b7c4ff",
        "surface-container": "#1c1f29",
        "on-primary-fixed-variant": "#004f53",
        "on-error": "#690005",
        "surface-dim": "#0f131c",
        "surface-tint": "#00dce6",
        "on-surface": "#dfe2ef",
        "surface-container-highest": "#31353f",
        "primary-container": "#00f2fe",
        primary: "#e0fdff",
        tertiary: "#f8f6ff",
        "on-tertiary-fixed": "#001452",
        "on-secondary-container": "#fffbff",
        "inverse-primary": "#00696f",
        "on-secondary-fixed": "#3e001e",
        "inverse-surface": "#dfe2ef",
        error: "#ffb4ab",
        background: "#0f131c",
        "on-primary-container": "#006a70",
        "on-background": "#dfe2ef",
        "tertiary-fixed": "#dde1ff",
        secondary: "#ffb0c9",
        "surface-variant": "#31353f",
        "on-primary-fixed": "#002022",
        outline: "#849495",
        "on-tertiary-fixed-variant": "#0038b6",
        "surface-bright": "#353943",
        surface: "#0f131c",
        "on-surface-variant": "#b9cacb",
        "secondary-fixed-dim": "#ffb0c9",
        "surface-container-low": "#181b25",
        "primary-fixed": "#6ff6ff",
        "on-secondary": "#640034",
        "inverse-on-surface": "#2c303a",
        "surface-container-high": "#262a34",
        "tertiary-container": "#d2d9ff",
        "outline-variant": "#3a494b",
        "on-tertiary": "#002682",
        "on-error-container": "#ffdad6",
        "on-primary": "#00373a",
        "error-container": "#93000a",
        "surface-container-lowest": "#0a0e17",
      },
      spacing: {
        "space-lg": "1.25rem",
        "space-md": "0.75rem",
        "card-padding-desktop": "1.25rem",
        "space-xl": "1.5rem",
        "screen-margin-desktop": "1.5rem",
        "space-3xl": "2.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "screen-margin-mobile": "1rem",
        "gutter-sm": "0.5rem",
        "gutter-md": "0.75rem",
        "gutter-lg": "1rem",
        "space-base": "1rem",
        "space-2xs": "0.125rem",
        "card-padding-mobile": "0.875rem",
        "space-2xl": "2rem",
      },
      fontFamily: {
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["20px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-mono-md": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "data-mono-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "odds-display": ["22px", { lineHeight: "26px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
